== Names and scopes

=== Names

`name: /\$?[^\W\d]\w*/`

A *name* is a string consisting of letters, underscores or digits. The first character may not be a digit. 

The first character may optionally be `$`, in which case the name is considered *escaped*. An escaped name is the same as an unescaped name, except in that it always lexes as a name, even if it is a <<reserved-words,reserved word>>.

=== Reserved words

A *reserved word* is a word which cannot be used as an <<names,unescaped name>>.

The list of reserved words is:

* `assert`
* `break`
* `check`
* `continue`
* `def`
* `for`
* `if`
* `import`
* `not`
* `pass`
* `return`
* `while`

=== Symbols

A *symbol* is a language construct that can be referred to by a name in the program. 

The following language constructs may be symbols:

* <<namespaces,namespaces>>
* <<variables,variables>>
* <<callables,callables>>
* <<types,types>>
* telemetry channels
* parameters
* enum constants
TODO members?
TODO you're selecting a member of a value--not referring to a static member. when you say a.b you're asking for a comp to be performed

=== Scopes

A *scope* is a mapping of names to symbols, accessed via some region of the source code.
TODO a scope IS a REGION

The *global scope* is the scope accessible throughout the entire source code.

Each <<functions,function>> has a *function scope*, accessible in its body.

The *resolving scope* is the most specific scope that some part of the source code has access to.

Scopes may have a *parent scope*:

* The parent scope of a function scope is the global scope.
* The global scope does not have a parent scope.

=== Name groups

Scopes are divided into *name groups*.

The list of name groups is:

* The *<<values,value>> name group*
* The *<<types,type>> name group*
* The *<<callables,callable>> name group*

Each name group only contains names which map to their particular language construct, or namespaces with the same property, recursively.
TODO Maybe could remove this line

TODO explain why we need this
Name groups do not intersect.

> This means that the names of callables, types and values never conflict.  WITH EACH OTHER

Name groups are accessed via syntactic context.
TODO this is really just an explanation

TODO type names should NOT be expressions


TODO A.b is an expr, A is an expr, b is not an expression. A.b is a dot expression. b is not an expression, it's part of a 
TODO Does it refer to something that has a scope, or does it refer to something that has members.

> For instance, the type name group is accessible anywhere in the source code where a type name is expected, such as a <<variable-definition,variable definition>> type annotation, or a <<function-definition,function definition>> return type.

The *resolving name group* is the name group that a name should be resolved in, based on its syntactic context.

=== Namespaces

A *namespace* is a mapping of names to symbols, associated with a name.

=== Qualified names

A *qualified name* is one of:

* A name
* A qualified name, followed by a `.`, followed by a name

The *qualifier* is the qualified name to the left of the `.`.

To resolve a qualified name in a name group:

. If there is no qualifier:
.. Resolve the name in the resolving scope.
.. If the name fails to be resolved, resolve the name in the parent scope of the resolving scope.
. Otherwise:
.. Resolve the qualifier.
.. If the qualifier is an expression, resolution is handled by the rules of <<member-access-expression,member access>>.
.. If the qualifier is not a namespace, an error is raised.
.. Resolve the name in the qualifier namespace.

If at any point a name fails to be resolved, an error is raised, unless otherwise specified.

A *fully-qualified name* is a qualified name which is not itself a qualifier.
TODO names are semantic, ident is syntactic
TODO you can't actually tell at syntax level what is a fqn
If a fully-qualified name resolves to a namespace, an error is raised.

_Tests:_ link:test/fpy/test_imports.py#L343[1,title="test/fpy/test_imports.py::TestImportNamespaceIsolation::test_module_name_not_usable_as_value"]

TODO you can think of the dict as "importing definitions"


> Namespace symbols cannot be used anywhere, so this forces names to resolve to something "useful"

TODO I'm not sure this is clear what this means. The idea here is that the full qualified name should always reference SOMETHING--cannot just put Svc in place of a type, even though Svc does resolve in type name group and global scope.

=== Definitions

A *definition* is a language construct that introduces a name-to-<<symbols,symbol>> mapping as apart of a <<scopes,scope>> and <<name-groups,name group>>.

The list of definitions is:

* <<variable-definition,Variable definitions>>
* <<function-definition,Function definitions>>
